# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DoctorSearch' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DoctorSearch
  
  target 'DataManager' do
      inherit! :search_paths
      # Pods for DataManager
      pod 'Alamofire', '~> 4.7'
  end
  
  target 'DoctorSearchTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DoctorSearchUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
